---
  - name: static web site
    cloudformation:
      stack_name: "Week-1"
      state: present
      region: "ap-southeast-1"
      disable_rollback: true
      template: "cfn-templates/week1.yml"
      stack_policy: "policies/cloudformation/stack-policy.json"
      template_parameters:
        BucketName: "{{bucket_name}}"
